# Map Continued .... 

In [1]:
str = ['Sonu','Sandeep','Arvind','Waseem','Anirudh','Sekhar','Chndu']

In [6]:
c = 0
for i in str:
    if (i[0]=='S'):
        c = c+1
print(c)

3


In [ ]:
# same functionalities with map function
map(function,list)

In [7]:
map(lambda x:x[0] == 'S' ,str)

In [8]:
list(map(lambda x:x[0] == 'S' ,str))

[True, True, False, False, False, True, False]

In [9]:
sum(map(lambda x:x[0] == 'S' ,str))

3

In [12]:
lst1 = [2,3,4,5]
lst2 = [4,5,6,7]
# lst3= [8,15,24,35]

In [15]:
lst3 = list(map(lambda x,y:x*y,lst1,lst2))
lst3

[8, 15, 24, 35]

In [19]:
str1=['Sonu','Sekahr','Shishir','Sandeep','Anirudh','Arvind','Waseem']
str2=['Kumar','Kumar','Pandey','Patel','Chakra','Yadav','Ahmed']
# o/p == ['Sonu Kumar','Sekhar Kumar','Shishir Pandey'.........]

In [27]:
list(map(lambda x,y:x+" "+y,str1,str2))

['Sonu Kumar',
 'Sekahr Kumar',
 'Shishir Pandey',
 'Sandeep Patel',
 'Anirudh Chakra',
 'Arvind Yadav',
 'Waseem Ahmed']

In [31]:
lst1 = [2,3,4,5]
lst2 = [4,5,6,7]
lst1+lst2

[2, 3, 4, 5, 4, 5, 6, 7]

In [45]:
c = []
for i in range(1,6):
    c.append(i*i)
print(c)

[1, 4, 9, 16, 25]


In [39]:
import numpy as np
arr1= np.array(lst1)
arr2=np.array(lst2)
arr1+arr2

array([ 6,  8, 10, 12])

In [40]:
arr1-arr2

array([-2, -2, -2, -2])

In [41]:
arr1*arr2

array([ 8, 15, 24, 35])

In [42]:
arr1/arr2

array([ 0.5       ,  0.6       ,  0.66666667,  0.71428571])

In [32]:
lst1-lst2

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [33]:
lst1*lst2

TypeError: can't multiply sequence by non-int of type 'list'

# filter : 
* syntax:
* filter(function,list)

In [46]:
lst= [2,4,5,6,7,8,9,10]
lst1 =[]
for i in lst:
    if (i%2 ==0):
        lst1.append(i)
print(lst1)

[2, 4, 6, 8, 10]


In [47]:
filter(lambda x:x%2==0,lst)

In [48]:
list(filter(lambda x:x%2==0,lst))

[2, 4, 6, 8, 10]

In [50]:
lst1 = ['Bangalore','Pune','Mumbai','Hyd','Chennai','Maharastra']
#lst2 = ['Mumbai','Maharastra']

In [52]:
c = []
for i in lst1:
    if i in('Mumbai','Maharastra'):
        c.append(i)
print(c)       

['Mumbai', 'Maharastra']


In [53]:
list(filter(lambda x:x.startswith('M'),lst1))

['Mumbai', 'Maharastra']

In [54]:
input_list = ['hdjk', 'salsap', 'sherpa']

In [57]:
c = []
for i in input_list:
    if i.startswith('s') and i.endswith('p'):
        c.append(i)
print(c)  

['salsap']


# Reduce function

In [59]:
from functools import reduce

In [ ]:
# pip install functools -- anoconda prompt

In [60]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [62]:
c = 0
for i in range(1,11):
    c=c+i
print(c)

55


In [63]:
# 1+2+3+4+5+6+7...10 = 55
reduce(lambda x,y:x+y,range(1,11))

55

In [64]:
# 1,2,3,4 = 1*2*3*4
reduce(lambda x,y:x*y,range(1,5))

24

In [65]:
lst1= [10,20,40,0,1,20,40,50]
#maximum = 50
#minimum = 0

### reduce(function,list)

In [66]:
reduce(lambda x,y: x if x> y else y, lst1)

50

In [67]:
reduce(lambda x,y: x if x <  y else y, lst1)

0